const data = [
  {
    category: "arts_and_literature",
    id: "622a1c3a7cc59eab6f9513a7",
    correctAnswer: "Don Quixote",
    incorrectAnswers: [
      "The Diary of a Chambermaid",
      "The Neverending Story",
      "Orlando Furioso",
    ],
    question: { text: "In which book does 'Alonso Quijano' appear?" },
    tags: ["literature", "fictitious_characters", "arts_and_literature"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  {
    category: "food_and_drink",
    id: "622a1c367cc59eab6f9502c5",
    correctAnswer: "A type of apple ",
    incorrectAnswers: [
      "A type of pear",
      "A type of peach",
      "A type of apricot",
    ],
    question: { text: "What is a 'Blenheim Orange'?" },
    tags: ["food", "food_and_drink", "fruit"],
    type: "text_choice",
    difficulty: "hard",
    regions: [],
    isNiche: false,
  },
  // {
  //   category: "arts_and_literature",
  //   id: "622a1c397cc59eab6f950f75",
  //   correctAnswer: "Stephen King",
  //   incorrectAnswers: ["H. P. Lovecraft", "Edgar Allan Poe", "Jack Vance"],
  //   question: { text: "Which author wrote 'Skeleton Crew'?" },
  //   tags: ["arts_and_literature"],
  //   type: "text_choice",
  //   difficulty: "hard",
  //   regions: [],
  //   isNiche: false,
  // },
  // {
  //   category: "arts_and_literature",
  //   id: "622a1c347cc59eab6f94f98b",
  //   correctAnswer: "Gone With the Wind",
  //   incorrectAnswers: [
  //     "Heart of Darkness",
  //     "Master and Commander",
  //     "Brideshead Revisited",
  //   ],
  //   question: { text: "Which book contains the character 'Scarlett O'Hara'?" },
  //   tags: ["fictitious_characters", "literature", "arts_and_literature"],
  //   type: "text_choice",
  //   difficulty: "medium",
  //   regions: [],
  //   isNiche: false,
  // },
  // {
  //   category: "music",
  //   id: "622a1c3d7cc59eab6f951c46",
  //   correctAnswer: "Just like the ones I used to know",
  //   incorrectAnswers: [
  //     "Sharing kisses in the snow",
  //     "We'll be going with the flow",
  //     "Walking to your favourite show",
  //   ],
  //   question: {
  //     text: "Bing Crosby famously sang 'I'm dreaming of a white Christmas'', what is the next line?",
  //   },
  //   tags: ["christmas", "lyrics", "general_knowledge"],
  //   type: "text_choice",
  //   difficulty: "easy",
  //   regions: [],
  //   isNiche: false,
  // },
  // {
  //   category: "society_and_culture",
  //   id: "6463395701d576cfac3aa362",
  //   correctAnswer: "Australia",
  //   incorrectAnswers: ["Canada", "The Republic of Ireland", "United States"],
  //   question: {
  //     text: "In which country is the Samuel Griffith Society headquartered, dedicated to upholding the constitution of said nation?",
  //   },
  //   tags: ["law", "society_and_culture", "government"],
  //   type: "text_choice",
  //   difficulty: "hard",
  //   regions: [],
  //   isNiche: false,
  // },
  // {
  //   category: "science",
  //   id: "622a1c377cc59eab6f95058c",
  //   correctAnswer: "The thereputic effects of bathing",
  //   incorrectAnswers: ["Plasma", "Balinese culture", "Victims of crime"],
  //   question: { text: "What is balneology the study of?" },
  //   tags: ["science", "words"],
  //   type: "text_choice",
  //   difficulty: "hard",
  //   regions: [],
  //   isNiche: false,
  // },
  // {
  //   category: "general_knowledge",
  //   id: "63951fffe55fa75b149597b7",
  //   correctAnswer: "Orange",
  //   incorrectAnswers: ["Red", "Blue", "Purple"],
  //   question: { text: "What colour do you get when you mix yellow with red?" },
  //   tags: ["colours", "general_knowledge"],
  //   type: "text_choice",
  //   difficulty: "easy",
  //   regions: [],
  //   isNiche: false,
  // },
  // {
  //   category: "geography",
  //   id: "623389060161109f922aacc1",
  //   correctAnswer: "Tasman",
  //   incorrectAnswers: ["Southern", "Antipodal", "Indian"],
  //   question: {
  //     text: "Which sea is located between Australia and New Zealand?",
  //   },
  //   tags: ["geography"],
  //   type: "text_choice",
  //   difficulty: "medium",
  //   regions: [],
  //   isNiche: false,
  // },
  // {
  //   category: "sport_and_leisure",
  //   id: "64824df37778562fd76a95e6",
  //   correctAnswer: "The Luge",
  //   incorrectAnswers: ["Skeleton", "Bobsleigh", "Curling"],
  //   question: {
  //     text: "What is the name of the winter Olympic sport in which you ride a sled face up and feet first?",
  //   },
  //   tags: ["winter_sports", "sport", "olympics"],
  //   type: "text_choice",
  //   difficulty: "hard",
  //   regions: [],
  //   isNiche: false,
  // },
];

export default data;